#!/usr/bin/env zsh

export CLICOLOR=1

# 10ms timeout required to map 'jk' to vi-cmd-mode
export KEYTIMEOUT=10
export QUOTING_STYLE=literal
export TERM=xterm-256color

# Make Neovim the default editor
export EDITOR="nvim";

# History
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=65536;
export SAVEHIST=65536;
export HISTORY_IGNORE="(ls|cd|pwd|exit|cd ..|..|...|....|date|j *)"

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";

# Highlight section titles in manual pages
export LESS_TERMCAP_md="${yellow}";

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto";

# Link Homebrew casks in `/Applications` rather than `~/Applications`
export HOMEBREW_CASK_OPTS="--appdir=/Applications";

# Set less tab size to 2
export LESS="-F -X -R --tabs 2 $LESS"

# https://formulae.brew.sh/formula/ruby-build
# https://github.com/rbenv/ruby-build/issues/1429
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
