#!/usr/bin/env zsh

export PATH="/usr/local/sbin:$PATH"
export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"

export PATH="/usr/local/opt/python/libexec/bin:$PATH"

export PATH="$HOME/.rbenv/bin:$PATH"

export PATH="$HOME/.cargo/bin:$PATH"

export PATH="$HOME/.bin/:$PATH"
