#!/usr/bin/env zsh

export PATH="/usr/local/sbin:$PATH";
export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH";
export PATH="$HOME/.rvm/bin:$PATH";

# Use gnu-sed over the default sed
#export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH";
#export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH";
